rename "Experiments" -> "Tasks" for terminology consistency
senseye-inc/senseye-react-native-sdk pull request #1
Opened 2021-04-10 00:31 UTC by tam-nguyen-senseye

"Experiment" is somewhat of a misnomer now and made more sense back when our tasks were conducted in an experimental setting. Meanwhile, "Task" has become the commonly accepted term, communicated both internally and externally. Updating the codebase to reflect this now will bring consistency and avoid any potential misunderstanding.

2021-04-12 16:22 UTC, Haplo-Dragon requested changes
We should regenerate the docs - they still refer to "Experiments". Other than that, looks good!

2021-04-12 16:53 UTC, Haplo-Dragon approved these changes
:+1:

2021-04-12 19:52 UTC, tam-nguyen-senseye commented
> We should regenerate the docs - they still refer to "Experiments". Other than that, looks good!

all docs will be regenerated in one go before version release

2021-04-13 19:02 UTC, ach206 approved these changes

2021-04-14 13:26 UTC, merged