Feature/ios UI updates
senseye-inc/senseye-react-native-sdk pull request #25
Opened 2021-06-24 18:07 UTC by ach206

- Ditched `react-native-picker` for `react-native-dropdown-picker` for better UI consistency/functionality amongst iOS and android
- Senseye themed styling
![new-sdk-dropdown-picker](https://user-images.githubusercontent.com/39183173/123311625-ff911280-d4ec-11eb-9b15-1b0163fce7e7.png)

2021-06-24 20:10 UTC, Haplo-Dragon commented on src/components/surveys/Demographic.tsx
> +            value={String(bedHour)}
I might be misunderstanding here - is there a reason to process the hours and minutes as strings instead of a number or Date type?

2021-06-25 16:38 UTC, ach206 commented on src/components/surveys/Demographic.tsx
> +            value={String(bedHour)}
exactly what you said in the standup meeting, due to textInput

2021-06-25 16:47 UTC, Haplo-Dragon commented on src/components/surveys/Demographic.tsx
> +            value={String(bedHour)}
Cool - everything else looks good! :+1:

2021-06-25 16:47 UTC, Haplo-Dragon approved these changes

2021-06-25 21:32 UTC, tam-nguyen-senseye requested changes

2021-06-25 21:32 UTC, tam-nguyen-senseye commented on package.json
> +    "react-native-svg": "^12.1.1",
is there a reason for adding this as a direct dependency? i had removed this in an earlier commit lol

it's already been added as a peerDependency for the sdk and as a direct dependency for the example, so that should be sufficient

2021-06-29 16:35 UTC, ach206 commented on package.json
> +    "react-native-svg": "^12.1.1",
ah interesting, ya it must of snuck in there when i did yarn install. i'll remove it

2021-06-29 16:56 UTC, merged